run:
  concurrency: 12
  deadline: 120s
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  funlen:
    lines: 76

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dupl
    - errorlint
    - exportloopref
    - forcetypeassert
    - funlen
#    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - golint
 #   - gomnd
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
  fast: false

