run:
  concurrency: 12
  deadline: 120s
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - forbidigo
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - whitespace

fast: true

linters-settings:
  funlen:
    lines: 76
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(github.com/ccamel/go-graphql-subscription-example)
    custom-order: true
