language: go

go_import_path: github.com/ccamel/go-graphql-subscription-example

go:
  - 1.12.4

services:
  - docker

env:
  global:
    - CACHE_FOLDER=$HOME/docker-images

before_install:
  - travis_retry docker pull golang:1.12.4
  - travis_retry make gen-static
  - travis_retry make install-deps

jobs:
  include:
    - stage: build
      script:
        - make check
        - make build
    - stage: dockerize
      script:
        - make dockerize
