version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.14.1

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: make check
      - run: make build
      - run: make dockerize

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
  thanks:
    docker:
      - image: circleci/golang:1.14.1
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: make thanks

workflows:
  version: 2
  make:
    jobs:
      - build
      - thanks:
          filters:
            branches:
              only: master
