version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/golang:1.16.3'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - 'go-mod-v4-{{ checksum "go.sum" }}'
      - run: make build
      - run: make check
      - run: make dockerize
      - save_cache:
          key: 'go-mod-v4-{{ checksum "go.sum" }}'
          paths:
            - /go/pkg/mod
  thanks:
    docker:
      - image: 'circleci/golang:1.16.3'
    steps:
      - checkout
      - run: make thanks
workflows:
  version: 2
  make:
    jobs:
      - build
      - thanks:
          filters:
            branches:
              only: master
