name: Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-go:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: Build go project
        uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: build

  build-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build docker image
        uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: docker
